# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:  
  # airflow_settings.yaml
  connections:
  - conn_id: google-cloud-default-study-gcp
    conn_type: google_cloud_platform
    description: "Connection to GCP project study-gcp (dev) using service account keyfile"
    conn_extra: {
        "extra__google_cloud_platform__project": "study-gcp-398200",
        "extra__google_cloud_platform__scope": "https://www.googleapis.com/auth/cloud-platform",
        "extra__google_cloud_platform__keyfile_dict": {
          "type": "service_account",
          "project_id": "study-gcp-398200",
          "private_key_id": "",
          "private_key": "",
          "client_email": "",
          "client_id": "",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sa-geral%40study-gcp-398200.iam.gserviceaccount.com",
          "universe_domain": "googleapis.com"
        }
      }

  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name: env
      variable_value: dev
